### ISSUE TITLE
Add license

### ISSUE THREAD

**Issue by skyfaller** [MordecaiMalignatus/RSass#1]
Thanks for writing a river of news aggregator in Rust!

Could you [add a license for your code to your repo](https://help.github.com/en/github/building-a-strong-community/adding-a-license-to-a-repository), to make it clear that people are welcome to contribute?

I personally prefer the AGPL3. I agree with [Bruce Perens saying there are too many licenses](https://www.datamation.com/osrc/article.php/12068_3803101_2/Bruce-Perens-How-Many-Open-Source-Licenses-Do-You-Need.htm) creating license compatibility problems. That said, I'm ok with any license approved by the FSF and OSI. (Not that my opinion matters, since I'm just a random dude on the internet.)

**Comment by MordecaiMalignatus** [comment]
Sure thing, I'll do that after work tonight. GPL v3 most likely

**Comment by MordecaiMalignatus** [comment]
(keys do things when windows are in focus, sorry)
